### ISSUE TITLE
Config page broken in Confluence 6.x

### ISSUE THREAD

**Issue by bberenberg** [Atlas-Authority/MarkdownMacro#26]
Steps to repro:

Change confluence and data version to  6.13.6 in the pom.xml file and start it up. Go to http://localhost:1990/confluence/admin/plugins/markdown/config.action

```
java.lang.IllegalArgumentException: Method 'doDefault()' is not defined in action 'class com.atlassian.plugins.confluence.markdown.configuration.PluginAdminGetConfigurationAction'
	at com.opensymphony.xwork.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:305)
	at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:170)
	at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:35)
	at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:165)
	at com.atlassian.confluence.core.ConfluenceLicenseInterceptor.intercept(ConfluenceLicenseInterceptor.java:66)
	at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:165)
	at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:35)
	at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:165)
	at com.atlassian.confluence.validation.MessageHolderInterceptor.intercept(MessageHolderInterceptor.java:37)
	at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:165)
	at com.opensymphony.xwork.interceptor.AroundInterceptor.intercept(AroundInterceptor.java:35)
	at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:165)
	at com.atlassian.confluence.util.LoggingContextInterceptor.intercept(LoggingContextInterceptor.java:44)
	at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:165)
	at com.atlassian.confluence.core.CancellingInterceptor.intercept(CancellingInterceptor.java:21)
	at com.opensymphony.xwork.DefaultActionInvocation.invoke(DefaultActionInvocation.java:165)
```

Seems to be caused by https://community.atlassian.com/t5/Answers-Developer-Questions/How-to-fix-quot-Method-doDefault-is-not-defined-in-action-quot/qaq-p/572232?_ga=2.267623630.1737017415.1597007157-304524449.1596658838

This was caused by #22 

@DeagleGross can you please fix this?

**Comment by bberenberg** [comment]
Will be released on Monday.
