### ISSUE TITLE
Failure to load macro - SUPPORT-1675

### ISSUE THREAD

**Issue by boris-moduscreate** [Atlas-Authority/MarkdownMacro#67]
Customer is getting:

```
2022-06-29 07:50:01,859 ERROR [http-nio2-8090-exec-10] [common.error.jersey.ThrowableExceptionMapper] toResponse Uncaught exception thrown by REST service: null
 -- referer: https://confluence.<customerURL>.net/pages/resumedraft.action?draftId=807333671&draftShareId=c032b4c0-7fe2-4d4b-b8a1-a7583175a93e& | url: /rest/markdown-from-url/1.0/config/retrieve | traceId: b37b2e3da4d47e76 | userName: BF8911
java.lang.NullPointerException
	at com.atlassian.plugins.confluence.markdown.configuration.PluginAdminGetConfigurationAction.getMarkdownConfig(PluginAdminGetConfigurationAction.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

In the logs. See https://atlasauthority.atlassian.net/browse/SUPPORT-1675 for more info, and the logs are in https://atlasauthority.atlassian.net/browse/SUPPORT-1703

If I am reading PluginAdminGetConfigurationAction.java:54 correctly, it seems like the customer doesn't have any config that can be pulled using our key? Which is odd since the customer has saved, and then re-saved the config? Maybe the issue here is that we're getting something bad back in the network request? Can we get additional debug logs for that?

**Comment by boris-moduscreate** [comment]
@khanguyen88 can you take a look at what may be causing this?

**Comment by khanguyen88** [comment]
this looks like a legit bug. I tested using the same Confluence version as his and reproduced this issue.

**Comment by khanguyen88** [comment]
this could be the reason https://confluence.atlassian.com/doc/preparing-for-confluence-7-0-950280675.html#PreparingforConfluence7.0-Springupgrade
